/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'
import { proxy, useSnapshot } from 'valtio'



export default function Model(props) {
  const state = proxy({
    current: null,
    items:{
      red: "red",
      black: "#3B3A51",
      green: "green",
      blue: "#CED6FF",
      brown: "#D89942",
      pink: "#EA93FF",
      white: "#CED6FF",
      brownn: "#CB8A69"
    }
  })
  const snap = useSnapshot(state)
  const group = useRef()
  const { nodes, materials } = useGLTF('/girl.gltf')

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[6.97, -2.5, -0.14]}>
        <group position={[-27.19, -118.08, 35.46]}>
          <mesh
            geometry={nodes.Cylinder_copy_2.geometry}
            material={nodes.Cylinder_copy_2.material}
            
            position={[-0.46, -102.14, -7.81]}
            rotation={[0, -0.17, 0]}>
            <mesh
              geometry={nodes.Cylinder_copy_19.geometry}
              material={nodes.Cylinder_copy_19.material}
              material-color={snap.items.brownn}
              position={[0, 18.81, 0]}
            />
            <mesh
              geometry={nodes.Cylinder_copy_20.geometry}
              material={nodes.Cylinder_copy_20.material}
              position={[0, -9.5, 0]}
            />
            <mesh
              geometry={nodes.Cylinder_copy_21.geometry}
              material={nodes.Cylinder_copy_21.material}
              position={[0, -1.68, 0]}
            />
            <mesh
              geometry={nodes.Cylinder_copy_22.geometry}
              material={nodes.Cylinder_copy_22.material}
              position={[0, -12.45, 13.53]}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              geometry={nodes.Cylinder_copy_23.geometry}
              material={nodes.Cylinder_copy_23.material}
              position={[0, -18.81, 0]}
            />
            <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[0, -15.39, 0]} />
            <mesh
              geometry={nodes.Cylinder_copy_24.geometry}
              material={nodes.Cylinder_copy_24.material}
              position={[0, -15, 13]}
            />
            <mesh
              geometry={nodes.Cylinder_copy_25.geometry}
              material={nodes.Cylinder_copy_25.material}
              position={[0, -18.73, 13]}
            />
          </mesh>
          <mesh
            geometry={nodes.Cylinder_copy_3.geometry}
            material={nodes.Cylinder_copy_3.material}
            position={[-0.46, -37.64, -7.81]}
          />
          <mesh
            geometry={nodes.Cylinder_copy_4.geometry}
            material={nodes.Cylinder_copy_4.material}
            position={[0, 75.95, -11.19]}
          />
        </group>
        <group position={[26.81, -118.08, 35.46]}>
          <mesh
            geometry={nodes.Cylinder_copy_5.geometry}
            material={nodes.Cylinder_copy_5.material}
            
            position={[-0.46, -102.14, -7.81]}
            rotation={[0, 0.14, 0]}>
            <mesh
              geometry={nodes.Cylinder_copy_26.geometry}
              material={nodes.Cylinder_copy_26.material}
              position={[0, 18.81, 0]}
              material-color={snap.items.brownn}
            />
            <mesh
              geometry={nodes.Cylinder_copy_27.geometry}
              material={nodes.Cylinder_copy_27.material}
              position={[0, -9.5, 0]}
            />
            <mesh
              geometry={nodes.Cylinder_copy_28.geometry}
              material={nodes.Cylinder_copy_28.material}
              position={[0, -1.68, 0]}
            />
            <mesh
              geometry={nodes.Cylinder_copy_29.geometry}
              material={nodes.Cylinder_copy_29.material}
              position={[0, -12.45, 13.53]}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              geometry={nodes.Cylinder_copy_30.geometry}
              material={nodes.Cylinder_copy_30.material}
              position={[0, -18.81, 0]}
            />
            <mesh geometry={nodes.Cylinder_1.geometry} material={nodes.Cylinder_1.material} position={[0, -15.39, 0]} />
            <mesh
              geometry={nodes.Cylinder_copy_31.geometry}
              material={nodes.Cylinder_copy_31.material}
              position={[0, -15, 13]}
            />
            <mesh
              geometry={nodes.Cylinder_copy_32.geometry}
              material={nodes.Cylinder_copy_32.material}
              position={[0, -18.73, 13]}
            />
          </mesh>
          <mesh
            geometry={nodes.Cylinder_copy_6.geometry}
            material={nodes.Cylinder_copy_6.material}
            position={[-0.46, -37.64, -7.81]}
          />
          <mesh
            geometry={nodes.Cylinder_copy_7.geometry}
            material={nodes.Cylinder_copy_7.material}
            position={[0, 75.95, -11.19]}
          />
        </group>
        <group position={[55.04, 110.64, -10.26]}>
          <mesh
            geometry={nodes.Sphere_copy_2.geometry}
            material={nodes.Sphere_copy_2.material}
            
            position={[-37.99, 105.49, 37.1]}
            rotation={[0, 0, -0.72]}
          />
          <mesh
            geometry={nodes.Sphere_copy_3.geometry}
            material={nodes.Sphere_copy_3.material}
            position={[3.51, -24.61, -9.71]}
            material-color={snap.items.white}
            rotation={[0.16, 0.17, 0.81]}
          />
          <mesh
            geometry={nodes.Sphere_copy_4.geometry}
            material={nodes.Sphere_copy_4.material}
            position={[-17.65, 23.16, -0.67]}
            rotation={[0.16, 0.17, 0.81]}
          />
          <mesh
            geometry={nodes.Sphere_copy_5.geometry}
            material={nodes.Sphere_copy_5.material}
            position={[-56.67, 38.14, -1.08]}
            rotation={[0, 0, 0.75]}
          />
          <mesh
            geometry={nodes.Sphere_copy_6.geometry}
            material={nodes.Sphere_copy_6.material}
            position={[-41.98, 62.65, 10.7]}
            rotation={[0, 0, 0.75]}
          />
          <mesh
            geometry={nodes.Sphere.geometry}
            material={nodes.Sphere.material}
            position={[-66.51, 82.12, 13.88]}
            rotation={[0.44, 0, 0]}
          />
          <mesh
            geometry={nodes.Sphere_copy_7.geometry}
            material={nodes.Sphere_copy_7.material}
            position={[-54.91, 88.62, 30.39]}
          />
          <mesh
            geometry={nodes.Sphere_copy_8.geometry}
            material={nodes.Sphere_copy_8.material}
            position={[-66.97, 108.24, 39.6]}
            rotation={[0, 0, 0.54]}
          />
        </group>
        <group position={[0.65, 178.07, 51.19]} rotation={[-0.56, -0.05, -0.01]}>
          <mesh
            geometry={nodes.Torus.geometry}
            material={nodes.Torus.material}
            
            position={[-0.86, 7, 0]}
            rotation={[0, 0, -2.72]}
          />
        </group>
        <group position={[-136.53, 79.87, 29.78]} scale={[-1, 1, 1]}>
          <group position={[93.16, -28.13, 3.57]} rotation={[0, -0.05, 0]} scale={[0.93, 0.94, 0.93]}>
            <mesh
              geometry={nodes.Cylinder_8.geometry}
              material={nodes.Cylinder_8.material}
              position={[16.27, -6.52, -0.1]}
              rotation={[0, 0, 0.94]}
            />
            <mesh
              geometry={nodes.Cylinder_7.geometry}
              material={nodes.Cylinder_7.material}
              position={[-10.7, 8.2, 0.1]}
              rotation={[0, 0, 1.22]}
              material-color={snap.items.pink}
            />
          </group>
          <group position={[55.04, -32.4, 5.18]} rotation={[0.48, -0.86, 0.04]} scale={[1.11, 1.11, 1.11]}>
            <mesh
              geometry={nodes.Cylinder_8_1.geometry}
              material={nodes.Cylinder_8_1.material}
              position={[13.87, -7.77, -1.89]}
              rotation={[-0.01, 0.39, 1.07]}
            />
            <mesh
              geometry={nodes.Cylinder_7_1.geometry}
              material={nodes.Cylinder_7_1.material}
              position={[-20.98, 8.94, 4.03]}
              rotation={[-0.04, 0.06, 1.16]}
            />
          </group>
          <group position={[98.77, -26.59, -13.52]}>
            <mesh
              geometry={nodes.Cylinder_8_2.geometry}
              material={nodes.Cylinder_8_2.material}
              position={[16.27, -6.52, -0.1]}
              rotation={[0, 0, 0.94]}
            />
            <mesh
              geometry={nodes.Cylinder_7_2.geometry}
              material={nodes.Cylinder_7_2.material}
              position={[-10.7, 8.2, 0.1]}
              rotation={[0, 0, 1.22]}
            />
          </group>
          <group position={[92.74, -28.13, -29.75]} scale={[0.91, 0.92, 0.93]}>
            <mesh
              geometry={nodes.Cylinder_8_3.geometry}
              material={nodes.Cylinder_8_3.material}
              position={[16.27, -6.52, -0.1]}
              rotation={[0, 0, 0.94]}
            />
            <mesh
              geometry={nodes.Cylinder_7_3.geometry}
              material={nodes.Cylinder_7_3.material}
              position={[-10.7, 8.2, 0.1]}
              rotation={[0, 0, 1.22]}
            />
          </group>
          <mesh
            geometry={nodes.Cylinder_copy_8.geometry}
            material={nodes.Cylinder_copy_8.material}
            position={[44.78, -11.72, -13.58]}
            rotation={[0, 0, 1.22]}
          />
          <mesh
            geometry={nodes.Cylinder_copy_9.geometry}
            material={nodes.Cylinder_copy_9.material}
            position={[24.09, -5.26, -12.89]}
            rotation={[0, 0, 1.22]}
          />
          <mesh
            geometry={nodes.Cylinder_copy_10.geometry}
            material={nodes.Cylinder_copy_10.material}
            position={[-80.68, 32.87, -12.89]}
            rotation={[0, 0, 1.22]}
          />
          <mesh
            geometry={nodes.Cylinder_copy_11.geometry}
            material={nodes.Cylinder_copy_11.material}
            position={[-43.1, 19.19, -12.89]}
            rotation={[0, 0, 1.22]}
          />
        </group>
        <group position={[136.53, 79.87, 29.78]}>
          <group position={[93.16, -28.13, 3.57]} rotation={[0, -0.05, 0]} scale={[0.93, 0.94, 0.93]}>
            <mesh
              geometry={nodes.Cylinder_8_4.geometry}
              material={nodes.Cylinder_8_4.material}
              position={[16.27, -6.52, -0.1]}
              rotation={[0, 0, 0.94]}
            />
            <mesh
              geometry={nodes.Cylinder_7_4.geometry}
              material={nodes.Cylinder_7_4.material}
              position={[-10.7, 8.2, 0.1]}
              rotation={[0, 0, 1.22]}
            />
          </group>
          <group position={[55.04, -32.4, 5.18]} rotation={[0.48, -0.86, 0.04]} scale={[1.11, 1.11, 1.11]}>
            <mesh
              geometry={nodes.Cylinder_8_5.geometry}
              material={nodes.Cylinder_8_5.material}
              position={[13.87, -7.77, -1.89]}
              rotation={[-0.01, 0.39, 1.07]}
            />
            <mesh
              geometry={nodes.Cylinder_7_5.geometry}
              material={nodes.Cylinder_7_5.material}
              position={[-20.98, 8.94, 4.03]}
              rotation={[-0.04, 0.06, 1.16]}
            />
          </group>
          <group position={[98.77, -26.59, -13.52]}>
            <mesh
              geometry={nodes.Cylinder_8_6.geometry}
              material={nodes.Cylinder_8_6.material}
              position={[16.27, -6.52, -0.1]}
              rotation={[0, 0, 0.94]}
            />
            <mesh
              geometry={nodes.Cylinder_7_6.geometry}
              material={nodes.Cylinder_7_6.material}
              position={[-10.7, 8.2, 0.1]}
              rotation={[0, 0, 1.22]}
            />
          </group>
          <group position={[92.74, -28.13, -29.75]} scale={[0.91, 0.92, 0.93]}>
            <mesh
              geometry={nodes.Cylinder_8_7.geometry}
              material={nodes.Cylinder_8_7.material}
              position={[16.27, -6.52, -0.1]}
              rotation={[0, 0, 0.94]}
            />
            <mesh
              geometry={nodes.Cylinder_7_7.geometry}
              material={nodes.Cylinder_7_7.material}
              position={[-10.7, 8.2, 0.1]}
              rotation={[0, 0, 1.22]}
            />
          </group>
          <mesh
            geometry={nodes.Cylinder_copy_12.geometry}
            material={nodes.Cylinder_copy_12.material}
            position={[44.78, -11.72, -13.58]}
            rotation={[0, 0, 1.22]}
          />
          <mesh
            geometry={nodes.Cylinder_copy_13.geometry}
            material={nodes.Cylinder_copy_13.material}
            position={[24.09, -5.26, -12.89]}
            rotation={[0, 0, 1.22]}
          />
          <mesh
            geometry={nodes.Cylinder_copy_14.geometry}
            material={nodes.Cylinder_copy_14.material}
            position={[-80.68, 32.87, -12.89]}
            rotation={[0, 0, 1.22]}
          />
          <mesh
            geometry={nodes.Cylinder_copy_15.geometry}
            material={nodes.Cylinder_copy_15.material}
            position={[-43.1, 19.19, -12.89]}
            rotation={[0, 0, 1.22]}
          />
        </group>
        <group position={[0.11, 101.8, 26.36]}>
          <mesh
            geometry={nodes.Cylinder_copy_16.geometry}
            material={nodes.Cylinder_copy_16.material}
            position={[1.04, 63.75, 0]}
          />
          <mesh
            geometry={nodes.Cylinder_copy_17.geometry}
            material={nodes.Cylinder_copy_17.material}
            position={[0, -91.25, 0]}
          />
          <mesh
            geometry={nodes.Cylinder_copy_18.geometry}
            material={nodes.Cylinder_copy_18.material}
            position={[0, -36.75, 0]}
          />
        </group>
        <mesh
          geometry={nodes.Sphere_copy.geometry}
          material={nodes.Sphere_copy.material}
          position={[-12.86, 193.25, 52.15]}
        />
        <mesh
          geometry={nodes.Sphere_copy_1.geometry}
          material={nodes.Sphere_copy_1.material}
          position={[12.6, 193.25, 52.15]}
        />
        <mesh
          geometry={nodes.Cone_copy.geometry}
          material={nodes.Cone_copy.material}
          position={[-0.26, 188.43, 52.86]}
        />
        <mesh
          geometry={nodes.Cylinder_copy.geometry}
          material={nodes.Cylinder_copy.material}
          position={[-29.66, 190.08, 22.42]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.Cylinder_copy_1.geometry}
          material={nodes.Cylinder_copy_1.material}
          position={[33.34, 190.08, 22.42]}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
      <directionalLight intensity={0.75} decay={2} position={[-429, 318, 247.5]} rotation={[-0.91, -0.82, 0.52]} />
      <OrthographicCamera
        makeDefault={false}
        far={100000}
        near={-50000}
        position={[455.42, 157.7, 889.06]}
        rotation={[-0.21, 0.46, 0.09]}>
        <directionalLight
          intensity={0.75}
          decay={2}
          position={[850000, 1300000, 1000000]}
          rotation={[-0.92, 0.48, -0.34]}
        />
      </OrthographicCamera>
      <mesh
        geometry={nodes.Floor.geometry}
        material={nodes.Floor.material}
        position={[0, -277.2, 25]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/girl.gltf')
