/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/poly.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[1.75, -0.83, -0.04]}>
        <primitive object={nodes.spine} />
        <skinnedMesh geometry={nodes.Cube.geometry} material={materials['Material 3']} skeleton={nodes.Cube.skeleton} />
      </group>
      <mesh
        geometry={nodes.Sphere.geometry}
        material={nodes.Sphere.material}
        position={[-0.66, 2.25, 0.98]}
        scale={[-0.15, -0.12, 0.12]}
      />
      <mesh
        geometry={nodes.Sphere001.geometry}
        material={nodes.Sphere001.material}
        position={[0.51, 2.27, 0.98]}
        scale={[-0.15, -0.12, 0.12]}
      />
      <mesh geometry={nodes.Cone.geometry} material={nodes.Cone.material} position={[-0.03, 1.84, 0.97]} scale={0.22} />
    </group>
  )
}

useGLTF.preload('/poly.glb')
