/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/wobbly.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <OrthographicCamera makeDefault={false} far={50000} near={-50000} position={[1.24, -19.24, 1000]}>
        <directionalLight
          intensity={0.75}
          decay={2}
          position={[850000, 1300000, 1000000]}
          rotation={[-0.92, 0.48, -0.34]}
        />
      </OrthographicCamera>
      <mesh geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} />
    </group>
  )
}

useGLTF.preload('/wobbly.gltf')
